name: compatibility

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "17 8 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
      - uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed
        with:
          deno-version: v2.9.4
      - run: deno task verify
